import { useState, useEffect } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  CheckCircle,
  XCircle,
  Loader2,
  Download,
  Monitor,
  ListChecks,
  ShieldCheck,
  Clock,
  FileText,
} from "lucide-react";
import { fetchBugSummary, type VerificationSummary } from "@/lib/api";

interface ReportViewDialogProps {
  isOpen: boolean;
  onClose: () => void;
  bugId: string;
  bugDescription: string;
  appName: string;
  appPackage: string;
  bugStatus: string;
}

export function ReportViewDialog({
  isOpen,
  onClose,
  bugId,
  bugDescription,
  appName,
  appPackage,
  bugStatus,
}: ReportViewDialogProps) {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [summary, setSummary] = useState<VerificationSummary | null>(null);

  useEffect(() => {
    if (isOpen) {
      loadSummary();
    }
    return () => {
      setLoading(true);
      setError(null);
      setSummary(null);
    };
  }, [isOpen, bugId]);

  const loadSummary = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await fetchBugSummary(bugId);
      setSummary(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load report");
    } finally {
      setLoading(false);
    }
  };

  const buildDetailedReport = (): string => {
    if (!summary) return "";
    
    const stepsFormatted = summary.steps.map((s, i) => `  ${i + 1}. ${s}`).join("\n");
    
    return `╔══════════════════════════════════════════════════════════════════════════════╗
║                        PROVIFY VERIFICATION REPORT                          ║
╚══════════════════════════════════════════════════════════════════════════════╝

Generated: ${new Date(summary.timestamp).toLocaleString()}
Report ID: VR-${bugId.toUpperCase()}-${Date.now().toString(36).toUpperCase()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                 BUG DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Application:     ${appName}
Package:         ${appPackage}
Bug ID:          ${bugId}
Current Status:  ${bugStatus.toUpperCase()}

Bug Description:
${bugDescription}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                              VERIFICATION SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

┌─────────────────────────────────────────────────────────────────────────────┐
│ STATUS:          ${summary.status === "verified" ? "✓ BUG VERIFIED (REPRODUCED)" : "✗ NOT REPRODUCIBLE"}
│ CONFIDENCE:      ${summary.confidence} ${summary.confidence === "HIGH" ? "●●●" : summary.confidence === "MEDIUM" ? "●●○" : "●○○"}
└─────────────────────────────────────────────────────────────────────────────┘

Test Metrics:
  • Device:              ${summary.device_name || "Unknown"}
  • Devices Tested:      ${summary.devices_tested}
  • Reproduced:          ${summary.reproduced} time(s)
  • Not Reproduced:      ${summary.not_reproduced} time(s)
  • Success Rate:        ${summary.devices_tested > 0 ? Math.round((summary.reproduced / summary.devices_tested) * 100) : 0}%

Summary:
${summary.summary}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                              STEPS EXECUTED
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${stepsFormatted}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                             DETAILED OBSERVATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${summary.result}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Report generated by Provify - AI-Powered QA Bug Verification
© ${new Date().getFullYear()} Provify. All rights reserved.
`;
  };

  const downloadReport = () => {
    const report = buildDetailedReport();
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `provify_report_${bugId}_${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getConfidenceBadgeStyle = (confidence: string) => {
    switch (confidence) {
      case "HIGH":
        return "bg-emerald-500/20 text-emerald-400 border-emerald-500/30";
      case "MEDIUM":
        return "bg-yellow-500/20 text-yellow-400 border-yellow-500/30";
      case "LOW":
        return "bg-orange-500/20 text-orange-400 border-orange-500/30";
      default:
        return "bg-zinc-500/20 text-zinc-400 border-zinc-500/30";
    }
  };

  const isVerified = summary?.status === "verified";

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent 
        className="bg-zinc-900 border-zinc-800 text-zinc-100 max-w-2xl max-h-[90vh] overflow-hidden flex flex-col"
      >
        <DialogHeader className="shrink-0">
          <DialogTitle className="text-xl flex items-center gap-3">
            <FileText className="w-6 h-6 text-emerald-400" />
            Bug Verification Report
          </DialogTitle>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto pr-2 -mr-2">
          {/* Bug Info */}
          <div className="bg-zinc-800/50 rounded-lg p-4 mb-4">
            <div className="text-sm text-zinc-400 mb-1">{appPackage}</div>
            <div className="text-base text-zinc-100 line-clamp-2">{bugDescription}</div>
          </div>

          {/* Loading State */}
          {loading && (
            <div className="flex flex-col items-center justify-center py-12 gap-4">
              <Loader2 className="w-10 h-10 text-emerald-400 animate-spin" />
              <p className="text-sm text-zinc-400">Loading verification report...</p>
            </div>
          )}

          {/* Error State */}
          {error && !loading && (
            <div className="p-4 rounded-lg bg-red-500/10 border border-red-500/30">
              <div className="flex items-center gap-2 text-red-400 font-semibold mb-1">
                <XCircle className="w-5 h-5" />
                No Report Found
              </div>
              <p className="text-sm text-zinc-300">
                {error === "No verification summary found" 
                  ? "This bug has not been verified yet or has no stored report."
                  : error}
              </p>
            </div>
          )}

          {/* Report Content */}
          {!loading && !error && summary && (
            <div className="space-y-4">
              {/* Status Banner */}
              <div
                className={`p-4 rounded-lg border ${
                  isVerified
                    ? "bg-emerald-500/10 border-emerald-500/30"
                    : "bg-red-500/10 border-red-500/30"
                }`}
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    {isVerified ? (
                      <CheckCircle className="w-6 h-6 text-emerald-400" />
                    ) : (
                      <XCircle className="w-6 h-6 text-red-500" />
                    )}
                    <span
                      className={`text-lg font-bold ${
                        isVerified ? "text-emerald-400" : "text-red-400"
                      }`}
                    >
                      {isVerified ? "BUG VERIFIED" : "NOT REPRODUCIBLE"}
                    </span>
                  </div>
                  <Badge className={`${getConfidenceBadgeStyle(summary.confidence)} border px-3 py-1`}>
                    <ShieldCheck className="w-3 h-3 mr-1" />
                    {summary.confidence} Confidence
                  </Badge>
                </div>
              </div>

              {/* Metrics Section */}
              <div className="bg-zinc-800/50 rounded-lg p-4">
                <h3 className="text-sm font-semibold text-zinc-300 mb-3 flex items-center gap-2">
                  <Monitor className="w-4 h-4" />
                  Test Metrics
                </h3>
                <div className="grid grid-cols-4 gap-3">
                  <div className="text-center p-3 bg-zinc-800 rounded-lg">
                    <div className="text-sm font-bold text-zinc-100 truncate">{summary.device_name || "Unknown"}</div>
                    <div className="text-xs text-zinc-400">Device</div>
                  </div>
                  <div className="text-center p-3 bg-zinc-800 rounded-lg">
                    <div className="text-2xl font-bold text-zinc-100">{summary.devices_tested}</div>
                    <div className="text-xs text-zinc-400">Tested</div>
                  </div>
                  <div className="text-center p-3 bg-zinc-800 rounded-lg">
                    <div className="text-2xl font-bold text-emerald-400">{summary.reproduced}</div>
                    <div className="text-xs text-zinc-400">Reproduced</div>
                  </div>
                  <div className="text-center p-3 bg-zinc-800 rounded-lg">
                    <div className="text-2xl font-bold text-red-400">{summary.not_reproduced}</div>
                    <div className="text-xs text-zinc-400">Not Reproduced</div>
                  </div>
                </div>
              </div>

              {/* Summary Text */}
              <div className="bg-zinc-800/50 rounded-lg p-4">
                <h3 className="text-sm font-semibold text-zinc-300 mb-2 flex items-center gap-2">
                  <FileText className="w-4 h-4" />
                  Summary
                </h3>
                <p className="text-sm text-zinc-300">{summary.summary}</p>
              </div>

              {/* Steps Executed */}
              <div className="bg-zinc-800/50 rounded-lg p-4">
                <h3 className="text-sm font-semibold text-zinc-300 mb-3 flex items-center gap-2">
                  <ListChecks className="w-4 h-4" />
                  Steps Executed ({summary.steps.length})
                </h3>
                <div className="space-y-2 max-h-32 overflow-y-auto">
                  {summary.steps.map((step, index) => (
                    <div key={index} className="flex items-start gap-2 text-sm">
                      <span className="text-emerald-400 font-mono shrink-0 w-5">{index + 1}.</span>
                      <span className="text-zinc-300">{step}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Detailed Observations */}
              <div className="bg-zinc-800/50 rounded-lg p-4">
                <h3 className="text-sm font-semibold text-zinc-300 mb-2 flex items-center gap-2">
                  <FileText className="w-4 h-4" />
                  Detailed Observations
                </h3>
                <p className="text-sm text-zinc-400 whitespace-pre-wrap max-h-40 overflow-y-auto">
                  {summary.result}
                </p>
              </div>

              {/* Timestamp */}
              <div className="flex items-center gap-2 text-xs text-zinc-500">
                <Clock className="w-3 h-3" />
                <span>Verified: {new Date(summary.timestamp).toLocaleString()}</span>
              </div>
            </div>
          )}
        </div>

        <DialogFooter className="flex gap-2 pt-4 shrink-0 border-t border-zinc-800">
          {!loading && !error && summary && (
            <Button
              variant="outline"
              className="border-zinc-700 bg-zinc-800 text-zinc-100 hover:bg-zinc-700 gap-2"
              onClick={downloadReport}
            >
              <Download className="w-4 h-4" />
              Download Report
            </Button>
          )}
          <Button
            className="flex-1 bg-emerald-500 hover:bg-emerald-400 text-black font-semibold"
            onClick={onClose}
          >
            Close
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
